### ISSUE TITLE
Support for Svelte 5

### ISSUE THREAD

**Issue by jafhueppe** [TheDahoom/Sveltekit-seo#7]
Hey there,

thanks for your work here! 

I'm currently playing around with Svelte5 after it's release this weekend and I'm getting errors in `rune` mode:

```
✘ [ERROR] node_modules/.pnpm/sk-seo@0.4.2/node_modules/sk-seo/SEO.svelte:4:4 Cannot use `export let` in runes mode — use `$props()` instead [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/.pnpm/sk-seo@0.4.2/node_modules/sk-seo/SEO.svelte:4:4:
      4 │    export let title = "", description = "", keywords = "", canonical = "", siteName 
        ╵     ^
```

You get these errors by 
- generating svelte 5 app
- installing sk-seo
- opt-in runes mode, see [docs](https://svelte-5-preview.vercel.app/docs/runes#how-to-opt-in)

**Comment by TheDahoom** [comment]
Now I did some testing and this can easily be fixed by setting 
```svelte
 <svelte:options runes={false} />
```
The issue I'm facing now is that if I publish this now, everyone using svelte 4 will have their sites broken since runes is not an actual option for them:
``` Build failed with 1 error: unknown attribute 'runes' ```

For now you can do ```pnpm i "https://github.com/TheDahoom/Sveltekit-seo#svelte-5"``` although I wont update this branch with every new release.

**Comment by TheDahoom** [comment]
You could also funnel it through a wrapper component that disables it on the npm package:
```svelte
<svelte:options runes={false} />
<script>
    import Seo from 'sk-seo';
    export let props = {};
</script>
<Seo {...props} />
``` 
but that would cause descriptions and types to stop working so the best course of action would probably be to just copy https://github.com/TheDahoom/Sveltekit-seo/blob/svelte-5/SEO.svelte into your project and just use it as is.

**Comment by jafhueppe** [comment]
hey there, thanks for your reply.

If you publish it with a newer version, it only crashes on svelte4 apps that update to this explicit new version - correct me if I'm wrong.


I think I'll copy it into my project as suggested by you and update it there to svelte5

**Comment by TheDahoom** [comment]
It turns out that runes is automatically detected on a per file basis. setting ``compilerOptions: { runes: true },`` forces all the files in a project to be compiled in rune mode which is what's causing the issue. 

If you still want to use this flag you can use https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#dynamiccompileoptions and set the node modules folder to be exempt from this.

Thanks to benmccann and dudek for pointing this out in the svelte discord.
